### ISSUE TITLE
Impossible de sortir sur le web depuis la ligne de commande

### ISSUE THREAD

**Issue by adriens** [adriens/tickets-resto-nc#29]
Michèle a le souci sur le jar exectubale de api : ça part en timeout, en lien avec  #25

**Comment by adriens** [comment]
`10:11:53.089 [main] ERROR com.github.adriens.tickets.resto.nc.api.Main - ReferenceError: "Hash" is not defined. (http://www.ticketrestaurant.nc/media/system/js/modal.js#7)
`

je reproduis le souci, a voir avec les propriétés de la jvm en lgne de commande

**Comment by adriens** [comment]
Même avec les args jvm en command line ça passe pas :

`java -Dhttp.proxyHost=proxyweb -Dhttp.proxyPort=3128 -Dhttp.proxyUser=xxx -Dhttp.proxyPassword=xxx`

**Comment by noemienicolas** [comment]
Ca fonctionnait et j'ai bien le même soucis que vous désormais...

**Comment by adriens** [comment]
Je viens de rajouter ProxyConfig et ça passe de partout

**Comment by adriens** [comment]
IDE et ligne de commande

**Comment by adriens** [comment]
Juste avec host et port ça passe

**Comment by adriens** [comment]
```java
ProxyConfig proxyConfig = new ProxyConfig("proxyweb", 3128);
            
            TicketsRestaurantsServiceWrapper wrap = new TicketsRestaurantsServiceWrapper(proxyConfig,login, password);
```

```java
private void setUpAccount(ProxyConfig proxyConfig, String login, String password) throws Exception {
        // first perform login to webpage
        this.proxyConfig = proxyConfig;
        WebClient webClient = new WebClient(BrowserVersion.CHROME);
        webClient.getOptions().setProxyConfig(proxyConfig);
```

**Comment by adriens** [comment]
On eut aussi ajoute rlogin/mdp :+1: 
https://stackoverflow.com/questions/1576583/htmlunit-proxy-issue

**Comment by adriens** [comment]
OK, validé sur le poste de @noemienicolas : on sort bien sur le web, va falloir surcharger

**Comment by adriens** [comment]
...avec les credential en option

**Comment by adriens** [comment]
Validé sur le poste de @noemienicolas également, c'est donc la bonne approche, il va falloir cabler la possibilite d'in proxy dans le code.

Attention, il faut le cable proprement : on peut aussi utiliser l'api sans proxy ;-p

**Comment by adriens** [comment]
OK avec les proprités de runtime java.
