### ISSUE TITLE
Permettre de définir une date de début pour les transactions

### ISSUE THREAD

**Issue by darwiin** [adriens/tickets-resto-nc#35]
Permettre d'ajouter une date de début pour les transactions à récupérer afin de limiter le volume de données téléchargées dans le cadre d'une application mobile.

**Comment by adriens** [comment]
Excellente idée, justement, je cherchais des pistes d'optimisation pour le traffic web....mais vu qu'on télécharge la page en entier, je suis pas spur que retourner un subset fasse gagner du download...en revanche ça permettrait de sauver un peu de mémoire.

@darwiin tu en penses quoi ?

**Comment by adriens** [comment]
Quand on télécharge la page, on la chope en entier, il faudrait réussir à appliquer, durant la nav avec htmunit, le filtre de 25 max.

**Comment by darwiin** [comment]
@adriens Je pensais également à ça, mais après avoir regardé 5 minutes je n'ai pas trouvé comment le nombre d'éléments à afficher était passé à la page des transactions. D'autant que par défaut toutes les transactions sont affichées.
Pour ce qui est de retourner un subset, ça peut être intéressant mais plus d'un oint de vue pratique pour l'utilisateur de l'API. Je ne suis pas sûr que les changements en terme de mémoire soit significatifs.

**Comment by adriens** [comment]
@darwiin : et oui, strictement la même analyse, je suis allé fouiner sur la page pour essayer de jouer avec les paginations...mais awa pas moyen :smile:

**Comment by adriens** [comment]
On garde le ticket au chaud ? Ou je ferme ?

**Comment by adriens** [comment]
La transaction la moins coûteuse reste celle du solde...du coup, je m'étais dit que ce serait plus au client de garder l'info du solde en historique, local, juste pour savoir si l'achat passe... ou pas...histoire de pas défoncer le forfait...

**Comment by adriens** [comment]
Tu as vu, que lorsque l'on affiche la page dans le nva, on a le filtre...mais qur lorsqu'on le chope avec htmlunit, on a toute la page, j'essaierai de jouer avec js....
SInon, j'ai toruvé que le site était codé en joomla...

**Comment by darwiin** [comment]
@adriens on peut fermer le ticket, je passerai par le solde.

**Comment by adriens** [comment]
:+1:
