### ISSUE TITLE
Problème de synchro et impossible de se reconnecter à l'appli 

### ISSUE THREAD

**Issue by ioanadraghici** [adriens/tickets-resto-nc#91]
Hello :)

Depuis mi-août la synchro ne marche plus et lorsque j'essaie de me reconnecter à l'appli j'ai le message d'erreur suivant : "Mot de passe ou identifiant incorrect".

Sur le site http://www.ticketrestaurant.nc/ ma connexion fonctionne très bien, le seul changement c'est ce message d'information : 

![tickets-resto-nc](https://user-images.githubusercontent.com/32151131/64134672-ed337980-ce2b-11e9-91d1-926b346c402e.png)

Je me connecte toujours avec l'identifiant à 7 chiffres et j'ai testé avec 2 cartes TR différentes sur 2 appareils différents, le résultat est le même.

D'avance merci :)
Ioana

**Comment by adriens** [comment]
Hello  @ioanadraghici .
Pour l'appli mobile, l'API n'est actuellement plus accessible depuis l'international cf https://github.com/mbarre/ticketresto-nc-rest/issues/109 
Je 🤞 pour que ce souci soit réglé avant la semaine prochaine.

Du coup, l'appli mobile est figée. 😢 
L'API marche parfaitement depuis la NC. Si tu me trouvez un hébergeur pour une image docker, alors on pourrait contourner le souci très rapidement.
J'attends des news.

D'ici là, je t'encourage à suivre activement https://github.com/mbarre/ticketresto-nc-rest/issues/109, ainsi tu pourras suivre en direct les avancées.

**Comment by adriens** [comment]
COmme ce n'est pas un souci du SDK, je ferme le ticket. 👍

**Comment by adriens** [comment]
Merci de m'avoir fait u ticket, ça me fait bien plaisir davoir un ticket de ta part...je t'assigne... un **TOP ticket** !

**Comment by ioanadraghici** [comment]
> Hello @ioanadraghici .
> Pour l'appli mobile, l'API n'est actuellement plus accessible depuis l'international cf [mbarre/ticketresto-nc-rest#109](https://github.com/mbarre/ticketresto-nc-rest/issues/109)
> Je 🤞 pour que ce souci soit réglé avant la semaine prochaine.
> 
> Du coup, l'appli mobile est figée. 😢
> L'API marche parfaitement depuis la NC. Si tu me trouvez un hébergeur pour une image docker, alors on pourrait contourner le souci très rapidement.
> J'attends des news.

Quelle taille a l'image docker ? :-)

**Comment by adriens** [comment]
Je ne l'ai pas encore faite, je laissais Heroku le faire pouir moi.
je vais m'y coller, je pense que ce sera très petit, j'ai toute la stack dont j'ai besoin. C'était dans le pipe, je crois que c'est le moment d'y aller pour le coup.

**Comment by adriens** [comment]
C'est offciellement dans le pipe cf  #93

**Comment by adriens** [comment]
Je l'ai déja fait sur d'autres projets.

L'idée de dépoyer sur un NAS à la maison en NOIP me plaît bien 😍

**Comment by adriens** [comment]
Ca permet de viser également les Raspberry Pi 🎆

**Comment by adriens** [comment]
https://www.linkedin.com/pulse/release-faster-safer-break-monolithic-ci-fluid-micro-jobs-sales/

**Comment by ioanadraghici** [comment]
> Je l'ai déja fait sur d'autres projets.
> 
> L'idée de dépoyer sur un NAS à la maison en NOIP me plaît bien 😍

C'est pas mal l'idée du NAS :)

> Ca permet de viser également les Raspberry Pi 🎆

C'est pas mal l'idée du NAS et nous en avons 2 Raspberry Pi @home ;-)

**Comment by adriens** [comment]
J'en ai parlé hier aprem avec Ronan 😄

**Comment by adriens** [comment]
D'ailleurs, je parle bien à Ioana ou à Ronan ❔

**Comment by ioanadraghici** [comment]
> D'ailleurs, je parle bien à Ioana ou à Ronan ❔

C'est bien Ioana 😄
